SWAB/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SWAB_APP.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWAB_APP/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import *

# api versioning
router = routers.DefaultRouter()
router.register(r'customUsers', CustomUserView, 'customUsers')
router.register(r'refugios', RefugioView, 'refugios')
router.register(r'mascotas', MascotaView, 'mascotas')

urlpatterns = [
    path('', index, name='index'),
    path('api/v1/', include(router.urls)),
    path('registrar/usuario/', registrar_usuario, name='registrar_usuario'),
    path('registrar/refugio/', registrar_refugio, name='registrar_refugio'),
    path('registrar/mascota/<int:id_refugio>', registrar_mascota, name='registrar_mascota'),
    path('filtrar_usuarios/', filtrar_usuarios, name='filtrar_usuarios'),
    path('filtrar_refugios/', filtrar_refugios, name='filtrar_refugios'),
    path('detalles/usuario/<int:id_usuario>/', detalles_usuario, name='detalles_usuario'),
    path('detalles/refugio/<int:id_refugio>/', detalles_refugio, name='detalles_refugio'),
    path('detalles/mascota/<int:id_mascota>/', detalles_mascota, name='detalles_mascota'),
    path('signup/', signup_view, name='signup'),
    path('signin/', signin_view, name='signin'),
    path('signout/', signout_view, name='signout'),
    path('modulo/usuarios', ModuloUsuariosView.as_view(), name='modulo_usuarios'),
    path('modulo/refugios', modulo_refugios, name='modulo_refugios'),

]

SWAB_APP/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser, Group


# Create your models here.
class CustomUser(AbstractUser):
    TIPOS_USUARIO = [
        ('admin', 'Administrador'),
        ('director', 'Director'),
        ('adoptante', 'Adoptante'),
    ]
    tipo = models.CharField(max_length=20, choices=TIPOS_USUARIO, default='adoptante')
    
    @property
    def es_admin_grupo(self):
        return self.groups.filter(name='Administrador').exists()

    def __str__(self):
        return f"{self.first_name} ({self.tipo})"


class Refugio(models.Model):
    nombre = models.CharField(max_length=150)
    direccion = models.CharField(max_length=255)
    telefono = models.CharField(max_length=20)
    descripcion = models.TextField(blank=True)
    director = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='refugios')
    logo = models.ImageField(upload_to='refugios/', null=True, blank=True)

    def __str__(self):
        return f"{self.nombre} - Dirigido por {self.director.username}"

class EstadoSalud(models.TextChoices):
    SANO = 'sano', 'Sano'
    ENFERMO = 'enfermo', 'Enfermo'
    RECUPERACION = 'recuperacion', 'Recuperacion'

class Especies(models.TextChoices):
    PERRO = 'perro', 'Perro'
    GATO = 'gato', 'Gato'
    CONEJO = 'conejo', 'Conejo'

class Mascota(models.Model):
    ESTADO_CHOICES = (
        ('disponible', 'Disponible'),
        ('adoptado', 'Adoptado'),
    )

    SEXO_CHOICES = (
        ('macho', 'Macho'),
        ('hembra', 'Hembra'),
    )

    SIZE_CHOICES = (
        ('grande', 'Grande'),
        ('mediano', 'Mediano'),
        ('chico', 'Chico'),
    )

    nombre = models.CharField(max_length=100)
    especie = models.CharField(max_length=20, choices=Especies, default=Especies.PERRO, blank=True, null=True)
    edad = models.IntegerField()
    sexo = models.CharField(max_length=10, choices=SEXO_CHOICES, default='macho', blank=True, null=True)
    tam = models.CharField(max_length=20, choices=SIZE_CHOICES, default='mediano', blank=True, null=True, db_column='tamaño')
    estado_salud = models.CharField(max_length=20, choices=EstadoSalud, default=EstadoSalud.SANO, blank=True, null=True)
    foto = models.ImageField(upload_to='mascotas/')
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='disponible')
    refugio = models.ForeignKey(Refugio, on_delete=models.CASCADE, related_name='mascotas')

    def __str__(self):
        return self.nombre + " - " + self.especie


class Adopcion(models.Model):
    ESTADOS = (
        ('pendiente', 'Pendiente'),
        ('aprobada', 'Aprobada'),
        ('rechazada', 'Rechazada'),
    )
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)
    adoptante = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='adopciones')
    fecha_solicitud = models.DateField(auto_now_add=True)
    fecha_adopcion = models.DateField(null=True, blank=True)
    estado = models.CharField(max_length=20, choices=ESTADOS, default='pendiente')

SWAB_APP/forms.py
# api/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import *

class RefugioForm(forms.ModelForm):
    class Meta:
        model = Refugio
        fields = '__all__'
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'direccion': forms.TextInput(attrs={'class':'form-control'}),
            'telefono': forms.TextInput(attrs={'class':'form-control'}),
            'descripcion': forms.Textarea(attrs={'class':'form-control'}),
            'logo': forms.FileInput(attrs={'class':'form-control'}),
            'director': forms.Select(attrs={'class':'form-select'}),
        }

class MascotaForm(forms.ModelForm):
    class Meta:
        model = Mascota
        fields = '__all__'
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'especie': forms.Select(attrs={'class':'form-select'}),
            'edad': forms.NumberInput(attrs={'class':'form-control'}),
            'sexo': forms.Select(attrs={'class':'form-select'}),
            'tamaño': forms.Select(attrs={'class':'form-select'}),
            'estado_salud': forms.Select(attrs={'class':'form-select'}),
            'foto': forms.FileInput(attrs={'class':'form-control'}),
            'estado': forms.Select(attrs={'class':'form-select'}),
            'refugio': forms.Select(attrs={'class':'form-select'}),
        }

class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(label="Usuario")
    password = forms.CharField(label="Contraseña", widget=forms.PasswordInput)

SWAB_APP/views.py
from idlelib.rpc import request_queue

from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework import viewsets
from .serializer import CustomUserSerializer, RefugioSerializer, MascotaSerializer
from .models import *
from .forms import *
from django.contrib.auth import login, logout, authenticate, decorators
from django.db import transaction
from .decorators import grupo_requerido
from rest_framework.permissions import IsAuthenticated, DjangoModelPermissions

class CustomUserView(viewsets.ModelViewSet):
    serializer_class = CustomUserSerializer
    queryset = CustomUser.objects.all()
    
    permission_classes = [IsAuthenticated, DjangoModelPermissions]


class RefugioView(viewsets.ModelViewSet):
    serializer_class = RefugioSerializer
    queryset = Refugio.objects.all()
    
    permission_classes = [IsAuthenticated, DjangoModelPermissions]


class MascotaView(viewsets.ModelViewSet):
    serializer_class = MascotaSerializer
    queryset = Mascota.objects.all()
    
    permission_classes = [IsAuthenticated, DjangoModelPermissions]


@grupo_requerido('Administrador')
def registrar_usuario(request):
    if request.method == 'POST':
        pass1 = request.POST.get('password1')
        pass2 = request.POST.get('password2')
        
        if pass1 == pass2:
            try:
                with transaction.atomic():
                    usuario = CustomUser.objects.create_user(
                        first_name=request.POST.get('first_name'),
                        last_name=request.POST.get('last_name'),
                        username=request.POST.get('username'),
                        email=request.POST.get('email'),
                        password=pass1,
                        tipo=''
                    )
                    
                    tipo_seleccionado = request.POST.get('tipo')
                    
                    if tipo_seleccionado == 'admin':
                        grupo = Group.objects.get(name='Administrador')
                    elif tipo_seleccionado == 'director':
                        grupo = Group.objects.get(name='Director')
                    else:
                        grupo = Group.objects.get(name='Adoptante')
                    
                    usuario.groups.add(grupo)
                    
                    return redirect('modulo_usuarios')
                
            except Group.DoesNotExist:
                return render(request, 'registrar_usuario.html', {'error': 'El rol seleccionado no existe en el sistema'})
            
            except IntegrityError:
                return render(request, 'registrar_usuario.html', {
                    'error': 'El nombre de usuario o correo ya existe.',
                    'old_data': request.POST 
                })
        else:
            return render(request, 'registrar_usuario.html', {
                'error': 'Las contraseñas no coinciden',
                'old_data': request.POST
            })

    return render(request, 'registrar_usuario.html')


@grupo_requerido('Administrador')
def registrar_refugio(request):
    if request.method == 'POST':
        form = RefugioForm(request.POST, request.FILES)
        
        if form.is_valid():
            form.save()
            return redirect('modulo_refugios')
        else:
            return render(request, 'registrar_refugio.html', {
                'form': form, 
                'error': 'Por favor corrige los errores señalados abajo.'
            })
    else:
        form = RefugioForm()

    return render(request, 'registrar_refugio.html', {
        'form': form,
    })


@grupo_requerido('Director')
def registrar_mascota(request, id_refugio):
    refugio = get_object_or_404(Refugio, id=id_refugio)

    if request.method == 'POST':
        form = MascotaForm(request.POST, request.FILES)
        if form.is_valid():
            mascota = form.save(commit=False)
            mascota.refugio = refugio
            mascota.save()
            return redirect(f'/detalles/refugio/{id_refugio}/')
        else:
            return render(request, 'registrar_mascota.html', {
                'form': form,
                'refugio': refugio,
                'error': 'Datos incorrectos, revisa los campos.'
            })
    else:
        return render(request, 'registrar_mascota.html', {
            'form': MascotaForm(),
            'refugio': refugio,
        })


def signup_view(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            try:
                usuario = CustomUser.objects.create_user(
                    first_name=request.POST['first_name'],
                    last_name=request.POST['last_name'],
                    username=request.POST['username'],
                    email=request.POST['email'],
                    password=request.POST['password1']
                )
                
                try:
                    grupo_adoptante = Group.objects.get(name='Adoptante')
                    usuario.groups.add(grupo_adoptante) 
                except Group.DoesNotExist:
                    return render(request, 'signup.html', {
                        'error': 'Error interno: El grupo Adoptante no existe.',
                    })
                
                login(request, usuario)
                return redirect('index')
            
            except IntegrityError:
                return render(request, 'signup.html', {
                    'error': 'error al registrar usuario',
                })
        return render(request, 'signup.html', {
            'error': 'Las contraseñas no coinciden',
        })
    return render(request, 'signup.html')


def signin_view(request):
    if request.method == 'POST':
        user = authenticate(
            request=request,
            username=request.POST['username'],
            password=request.POST['password']
        )

        if user is None:
            return render(request, 'signin.html', {
                'error': 'usuario y/o contraseña incorrectos'
            })
        else:
            login(request, user)
            return redirect('index')
    else:
        form = CustomLoginForm()
    return render(request, 'signin.html', {'form': form})


@login_required(login_url='signin')
def signout_view(request):
    logout(request)
    return redirect('index')


def index(request):
    return render(request, 'index.html', {
        'user': request.user
    })


class ModuloUsuariosView(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    template_name = 'modulo_usuarios.html'
    
    # MIXIN 1: Configuración de Login
    login_url = 'signin' 
    
    # MIXIN 2: Configuración de Permisos
    
    permission_required = 'SWAB_APP.view_customuser' 
    
    raise_exception = True

    # Pasamos el contexto (variables) al HTML
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['u'] = self.request.user
        return context

#@grupo_requerido('Administrador')
#def modulo_usuarios(request):
#    return render(request, 'modulo_usuarios.html', {'u': request.user})


@grupo_requerido('Administrador')
def detalles_usuario(request, id_usuario):
    if request.method == 'GET':
        usuario = get_object_or_404(CustomUser, id=id_usuario)

        return render(request, 'detalle_usuario.html', {
            'usuario': usuario,
        })


def modulo_refugios(request):
    refugios = Refugio.objects.all()
    return render(request, 'modulo_refugios.html', {
        'user': request.user,
        'refugios': refugios,
    })


def detalles_refugio(request, id_refugio):
    if request.method == 'GET':
        refugio = get_object_or_404(Refugio, id=id_refugio)
        mascotas = Mascota.objects.filter(refugio=refugio)
        form = RefugioForm(instance=refugio)
        return render(request, 'detalle_refugio.html', {
            'refugio': refugio,
            'usuario': request.user,
            'form': form,
            'mascotas': mascotas,
        })


def detalles_mascota(request, id_mascota):
    if request.method == 'GET':
        mascota = get_object_or_404(Mascota, id=id_mascota)
        form = MascotaForm(instance=mascota)
        return render(request, 'detalle_mascota.html', {
            'usuario': request.user,
            'form': form,
            'mascota': mascota,
        })


def filtrar_usuarios(request):
    tipo = request.GET.get('tipo')
    if not tipo:
        return JsonResponse({'error': 'No se proporcionó tipo'}, status=400)

    usuarios = CustomUser.objects.filter(tipo=tipo).values('id', 'first_name', 'last_name', 'email', 'tipo')
    return JsonResponse(list(usuarios), safe=False)


def filtrar_refugios(request):
    id_usuario = request.GET.get('id_usuario')
    if not id_usuario:
        return JsonResponse({'error': 'No se proporcionó usuario'}, status=400)

    try:
        refugio = Refugio.objects.get(director_id=id_usuario)
        data = {
            'id': refugio.id,
            'nombre': refugio.nombre,
            'direccion': refugio.direccion,
        }
        return JsonResponse(data, safe=False)

    except Refugio.DoesNotExist:
        return JsonResponse({'mensaje': 'No se encontró refugio asociado'}, status=404)

SWAB_APP/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">SWAB PetCare</a>
        <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#menu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="menu">
            <ul class="navbar-nav ms-auto">
                {% block nav %}

                {% endblock %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'modulo_refugios' %}">Refugios</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signout' %}">Cerrar sesión</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">Registrarse</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signin' %}">Iniciar sesión</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>


{% block content %}

{% endblock %}

<footer class="bg-white text-dark-emphasis text-center py-3 mt-4">
    © 2025 SWAB PetCare | Todos los derechos reservados
</footer>

<script src="{% static 'js/bootstrap.min.js' %}"></script>

{% block scripts %}

{% endblock %}


</body>
</html>

SWAB_APP/templates/detalle_refugio.html
{% extends 'base.html' %}

{% block content %}
    <main class="container d-flex flex-row justify-content-around align-items-center p-5 ">
        <div class="container w-50 ">
            <h1 id="refugioNombre" class="display-1  ">{{ refugio.nombre }}</h1>
        </div>
        {% if perms.SWAB_APP.change_refugio or perms.SWAB_APP.delete_refugio or perms.SWAB_APP.add_mascota %}
            <div class="fab-container">
                <div class="fab fab-main">
                    <i class="bi bi-plus-lg">+</i>
                </div>

                {% if perms.SWAB_APP.change_refugio %}
                    <div class="fab fab-option">
                        <a id="btnEditar" title="Editar Refugio" class="">Editar</a>
                    </div>
                {% endif %}

                {% if perms.SWAB_APP.delete_refugio %}
                    <div class="fab fab-option">
                        <a id="btnEliminar" title="eliminar">Eliminar</a>
                    </div>
                {% endif %}

                {% if perms.SWAB_APP.add_mascota %}
                    <div class="fab fab-option">
                        <a href="{% url 'registrar_mascota' refugio.id %}" title="Nueva Mascota">Agregar mascota</a>
                    </div>
                {% endif %}
            </div>
        {% endif %}

        <div class="container w-25">
            {% if refugio.logo %}
                <img id="refugioLogo" src="{{ refugio.logo.url }}" alt="{{ refugio.nombre }}"
                     class="img-fluid rounded  w-100">
            {% endif %}
        </div>
    </main>

    <section class="text-center p-5 container">
        <p id="refugioDesc" class="text-dark-emphasis">{{ refugio.descripcion }}</p>
    </section>

    <section class="text-center p-5 container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                {% if mascotas %}
                    <h1 class="text-center display-5 py-3">Esperando compañía :(</h1>
                {% else %}
                    <h1 class="text-center display-3 py-3">No hay mascotas registradas</h1>
                {% endif %}
                <ul id="listaMascotas" class="list-group">

                </ul>
            </div>
        </div>
    </section>

    <div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="municipiosModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLabel">Actualizar</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>

                <div class="modal-body" id="body">
                    {{ error }}
                    <form id="refugioForm" enctype="multipart/form-data"
                          class="container">

                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <p id="mensaje" class="text-bg-success"></p>

{% endblock content %}

{% block scripts %}
    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== "") {
                const cookies = document.cookie.split(";");
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + "=")) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        function mascotaCard(mascota, lista) {
            const userHTML = document.createElement('li');
            userHTML.classList.add('list-group-item');
            userHTML.classList.add('d-flex');
            userHTML.classList.add('justify-content-center');
            userHTML.classList.add('border-0');
            userHTML.classList.add('mt-3');

            const card = document.createElement('div');
            card.classList.add('card');
            card.classList.add('w-50');

            const cardBody = document.createElement('div');
            cardBody.classList.add('card-body');
            cardBody.classList.add('text-center');

            const cardTitle = document.createElement('h3');
            cardTitle.textContent = (mascota.nombre).toUpperCase();

            const cardText = document.createElement('p');
            cardText.classList.add('card-text');
            cardText.textContent = (mascota.estado_salud);

            const a = document.createElement('a');
            a.classList.add('btn');
            a.classList.add('btn-success');
            a.classList.add('w-50');
            a.textContent = 'Ver';
            a.href = `/detalles/mascota/${mascota.id}/`;

            cardBody.appendChild(cardTitle);
            cardBody.appendChild(cardText);
            cardBody.appendChild(a);

            card.appendChild(cardBody);

            userHTML.append(card);

            lista.appendChild(userHTML);
        }

        const listaMascotas = document.getElementById('listaMascotas');
        const idRefugio = {{ refugio.id }};

        const obtenerRefugios = async () => {
            try {
                const r = await fetch(`/api/v1/refugios/${idRefugio}`)

                if (!r.ok) {
                    throw new Error(r.message)
                }

                const refugio = await r.json();

                if (refugio.mascotas.length === 0) {
                    const li = document.createElement('li');
                    li.textContent = "Sin mascotas registradas.";
                    listaMascotas.appendChild(li);
                } else {
                    refugio.mascotas.forEach(mascota => {
                        mascotaCard(mascota, listaMascotas);
                    })
                }

            } catch (e) {
                console.log(e);
            }
        }

        document.addEventListener('DOMContentLoaded', obtenerRefugios);


        const modal = new bootstrap.Modal(document.getElementById('formModal'));


        document.getElementById('btnEditar').addEventListener('click', (e) => {
            e.preventDefault();

            modal.show();
        });

        document.getElementById('refugioForm').addEventListener('submit', async (e) => {
            e.preventDefault();

            const id = {{ refugio.id }}
            const msg = document.getElementById('mensaje');

            const datos_actualizados = {
                nombre: document.getElementById('id_nombre').value,
                direccion: document.getElementById('id_direccion').value,
                telefono: document.getElementById('id_telefono').value,
                descripcion: document.getElementById('id_descripcion').value,
                director: document.getElementById('id_director').value
            }

            try {
                const r = await fetch(`/api/v1/refugios/${id}/`, {
                    method: 'PATCH',
                    headers: {
                        'Content-Type': 'application/json',
                        'Accept': 'application/json',
                        "X-CSRFToken": getCookie("csrftoken"),
                    },
                    body: JSON.stringify(datos_actualizados)
                });

                if (r.ok) {
                    const data = await r.json();
                    console.log(data);
                    msg.textContent = "✅ Usuario actualizado correctamente";
                    document.getElementById('refugioNombre').textContent = data.nombre;
                    const logo = document.getElementById('refugioLogo');
                    document.getElementById('refugioDesc').textContent = data.descripcion;
                    modal.hide();
                } else {
                    const error = await r.text();
                    msg.textContent = error;
                }
            } catch (e) {
                console.log(e);
                document.getElementById('mensaje').textContent = "⚠️ Error de conexión con el servidor.";
            }
        })

        document.getElementById('btnEliminar').addEventListener('click', async (e) => {
            e.preventDefault()
            const id = {{ refugio.id }};

            try {
                const r = await fetch(`/api/v1/refugios/${id}/`, {
                    method: 'DELETE',
                    headers: {
                        'Content-Type': 'application/json',
                        'Accept': 'application/json',
                        "X-CSRFToken": getCookie("csrftoken"),
                    }
                })

                if (r.ok) {

                    window.location.href = "{% url 'modulo_refugios' %}";
                } else {
                    const error = await r.text();
                    console.log(error)
                }
            } catch (e) {
                console.error(e);
                document.getElementById('mensaje').textContent = "⚠️ Error de conexión con el servidor.";
            }
        })

    </script>`
{% endblock %}`

SWAB_APP/templates/modulo_refugios.html
{% extends 'base.html' %}


{% block content %}

    <main class="container ">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                {% if refugios %}
                    <h1 class="text-center display-3 py-3">Refugios registrados</h1>
                {% else %}
                    <h1 class="text-center display-3 py-3">No hay refugios registrados</h1>
                {% endif %}
                <ul class="list-group">
                    {% for refugio in refugios %}
                        <li class="list-group-item d-flex justify-content-center border-0 mt-3">
                            <div class="card w-50">
                                {% if refugio.logo %}
                                    <img src="{{ refugio.logo.url }}" class="card-img-top object-fit-container"
                                         alt="{{ refugio.nombre }}">
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title">{{ refugio.nombre.upper }}</h5>
                                    <p class="card-text">{{ refugio.direccion }}</p>
                                    <a class="btn btn-success w-50" href="{% url 'detalles_refugio' refugio.id %}">Saber
                                        más</a>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% if perms.SWAB_APP.add_refugio %}
            <a class="btn btn-primary" href="{% url 'registrar_refugio' %}">Registrar nuevo refugio</a>
        {% endif %}
    </main>

{% endblock %}

SWAB_APP/templates/registrar_mascota.html
{% extends 'base.html' %}

{% block content %}
    <main class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                {{ error }}
                <form action="{% url 'registrar_mascota' refugio.id %}" method="POST" enctype="multipart/form-data"
                      class="card card-body mt-5">
                    <h1 class="text-center py-3">Registrar Mascota</h1>

                    {% csrf_token %}
                    {{ form.as_p }}

                    <button class="btn btn-primary">Guardar</button>
                </form>
            </div>
        </div>
    </main>
{% endblock content %}

SWAB_APP/templates/registrar_refugio.html
{% extends 'base.html' %}

{% block content %}
    <main class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                {{ error }}
                <form action="/registrar/refugio/" method="POST" enctype="multipart/form-data" class="card card-body mt-5">
                    <h1 class="text-center py-3">Registrar Refugio</h1>

                    {% csrf_token %}
                    {{ form.as_p }}

                    <button class="btn btn-primary">Guardar</button>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

SWAB_APP/templates/signin.html
{% extends 'base.html' %}

{% block content %}

    <main class="container w-100">
        <div class="row">
            <section class="col-md-4 offset-md-4 mt-5">
                <form method="POST" class="card card-body">
                    <h1 class="text-center">Signin</h1>
                    {{ error }}
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username">Username</label>
                        <input type="text" class="form-control" id="username" name="username" placeholder="Username">
                    </div>

                    <div class="mb-3">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password"
                               placeholder="Password">
                    </div>

                    <button class="btn btn-primary ">Login</button>
                </form>
            </section>
        </div>
    </main>

{% endblock %}